@echo off
echo Refreshing Instagram feed...
py -3 "%~dp0tools\scrape_social_feed.py"
echo Scraping Facebook (timeline, real posts only)...
py -3 "%~dp0tools\scrape_facebook_bulk.py"
echo Picking diverse mission manifest...
py -3 "%~dp0tools\pick_mission_manifest.py"
echo Building mission gallery...
py -3 "%~dp0tools\build_mission_gallery.py"
pause
